Separating Test and Build tasks to two actions
NWChemEx-Project/.github pull request #74
Opened 2023-02-13 06:56 UTC by quazirafi

**PR Type**

- [ ] Breaking change
- [ ] Feature
- [ ] Patch

**Brief Description**

This PR separates build and test tasks into two separate actions.

**Not In Scope**

Anything not related to separating build and test actions.

**PR Checklist**

- [ ] Documentation (comments, API, user, design, and developer as applicable)
    - [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
    - [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
    - [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
    - [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [ ] Testing (unit, integration, performance, as applicable)
    - [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
    - [Integration](https://nwchemex-project.github.io/.github/testing/integration.html)
    - [Performance](https://nwchemex-project.github.io/.github/testing/performance.html)
- [ ] Code adheres to organization standards
    - [C++](https://nwchemex-project.github.io/.github/coding/cxx/cxx_conventions.html)
    - [Python](https://nwchemex-project.github.io/.github/coding/python/python_conventions.html)
    - [Doxygen Conventions](https://nwchemex-project.github.io/.github/documenting/doxygen_conventions.html)
    - [reST Conventions](https://nwchemex-project.github.io/.github/documenting/rst_conventions.html)

**TODOs**

Nothing.

2023-02-15 16:52 UTC, ryanmrichard requested changes
Can you please:
- clean up the comments so they reflect what's going on instead of being copy/pasted and no longer relevant, 
- remove the stale commented out code (except the code coverage part, which needs to be re-enabled at some point), and 
- remove the binary file you checked in?

Thanks

2023-02-16 19:17 UTC, ryanmrichard requested changes
You still have the `.DS_store` binary thing, which shouldn't be checked in. 

Have you tested this PR and verified the tests run? Looking at `.github/workflows/c-cpp_tmpl.yaml` I don't see any calls to the testing action.

2023-02-16 19:17 UTC, ryanmrichard commented on actions/test/test.sh
> +################################################################################
```suggestion
```

2023-02-16 19:17 UTC, ryanmrichard commented on actions/build/build.sh
> +ctest_command=ctest
```suggestion
```

2023-02-16 21:20 UTC, quazirafi commented
> You still have the `.DS_store` binary thing, which shouldn't be checked in.
> 
> Have you tested this PR and verified the tests run? Looking at `.github/workflows/c-cpp_tmpl.yaml` I don't see any calls to the testing action.

1. I removed that **.DS_store** file. In my second last push it is showing that the file is removed. 
2. Yes, I tested for ParallelZone and it worked. See here please:
https://github.com/NWChemEx-Project/ParallelZone/actions/runs/4160768371
@ryanmrichard

2023-02-16 21:27 UTC, ryanmrichard commented
It's showing that it was renamed:

![image](https://user-images.githubusercontent.com/5280139/219490549-3fc6a5db-2c25-49c7-bbb1-641e09876050.png)

2023-02-16 21:47 UTC, quazirafi commented
> It's showing that it was renamed:
> 
> ![image](https://user-images.githubusercontent.com/5280139/219490549-3fc6a5db-2c25-49c7-bbb1-641e09876050.png)

Can you check now? @ryanmrichard

2023-02-16 21:56 UTC, quazirafi commented
Hopefully, it should be fine now. I also removed the header comments. @ryanmrichard

2023-02-16 22:07 UTC, quazirafi commented
Let me test one more time then we can merge this.

2023-02-16 22:26 UTC, quazirafi commented
It looks fine to me now. I just tested with ParallelZone again with all changes. @ryanmrichard

2023-02-16 23:36 UTC, quazirafi commented on actions/test/test.sh
> +################################################################################
done

2023-02-17 15:25 UTC, merged

2023-02-17 15:25 UTC, ryanmrichard commented
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/NWChemEx-Project/.github/actions/runs/4205137489) **New version**:[v0.0.2](https://github.com/NWChemEx-Project/.github/releases/tag/v0.0.2) **Changes**:[v0.0.1...v0.0.2](https://github.com/NWChemEx-Project/.github/compare/v0.0.1...v0.0.2)